scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090 ']