services:
  # Java App Service
  - type: web
    name: java-app
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
    port: 8080

  # Prometheus Service
  - type: web
    name: prometheus
    env: docker
    dockerfile:
      image: prom/prometheus:v2.44.0
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
    port: 10000
    disk:
      name: prometheus-data
      mountPath: /etc/prometheus
      sizeGB: 1

  # Grafana Service
  - type: web
    name: grafana
    env: docker
    dockerfile:
      image: grafana/grafana:9.5.2
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000
    port: 3000
    disk:
      name: grafana-data
      mountPath: /etc/grafana
      sizeGB: 1
