services:
  # Java App Service
  - type: web
    name: java-app
    env: docker
    buildCommand: ./build.sh # Replace with your actual build command
    startCommand: ./start.sh # Replace with your actual start command
    dockerfilePath: Dockerfile
    envVars:
    # Add environment variables here if needed
    ports:
      - port: 8080
        protocol: http

  # Prometheus Service
  - type: web
    name: prometheus
    env: image
    image:
      url: prom/prometheus:v2.44.0
    ports:
      - port: 10000
        protocol: http
    volumes:
      - source: ./prometheus.yml
        destination: /etc/prometheus/prometheus.yml

  # Grafana Service
  - type: web
    name: grafana
    env: image
    image:
      url: grafana/grafana:9.5.2
    ports:
      - port: 3000
        protocol: http
    restartPolicy: unless-stopped
    volumes:
      - source: ./datasources
        destination: /etc/grafana/provisioning/datasources
