services:
  - type: web
    name: java-app
    env: docker
    buildCommand: 'docker build -t java-app .'
    healthCheckPath: '/'
    envVars:
      - key: PORT
        value: '8080'

  - type: web
    name: prometheus
    env: docker
    dockerImage: 'prom/prometheus:v2.44.0'
    healthCheckPath: '/'
    envVars:
      - key: PORT
        value: '10000'

  - type: web
    name: grafana
    env: docker
    dockerImage: 'grafana/grafana:9.5.2'
    healthCheckPath: '/'
    envVars:
      - key: PORT
        value: '3000'
