services:
  - type: web
    name: java-app
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: '/'
    envVars:
      - key: PORT
        value: '8080'

  - type: web
    name: prometheus
    env: docker
    build:
      image: 'prom/prometheus:v2.44.0'
    healthCheckPath: '/'
    envVars:
      - key: PORT
        value: '10000'

  - type: web
    name: grafana
    env: docker
    build:
      image: 'grafana/grafana:9.5.2'
    healthCheckPath: '/'
    envVars:
      - key: PORT
        value: '3000'
