services:
  - type: web
    name: java-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: '/'
    envVars:
      - key: PORT
        value: '8080'

  - type: web
    name: prometheus
    runtime: image
    image:
      url: 'registry.hub.docker.com/library/prom/prometheus:v2.44.0'
    healthCheckPath: '/'
    envVars:
      - key: PORT
        value: '10000'

  - type: web
    name: grafana
    runtime: image
    image:
      url: 'registry.hub.docker.com/library/grafana/grafana:9.5.2'
    healthCheckPath: '/'
    envVars:
      - key: PORT
        value: '3000'
