services:
  - type: web
    name: java-app
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: '8080'
    port: 8080

  - type: web
    name: prometheus
    env: docker
    image: prom/prometheus:v2.44.0
    port: 10000
    envVars:
      - key: PORT
        value: '10000'
    disk:
      name: prometheus-data
      mountPath: /etc/prometheus
      sizeGB: 10 # Adjust the size as necessary

  - type: web
    name: grafana
    env: docker
    image: grafana/grafana:9.5.2
    restartPolicy: always
    port: 3000
    envVars:
      - key: PORT
        value: '3000'
    disk:
      name: grafana-data
      mountPath: /etc/grafana
      sizeGB: 10 # Adjust the size as necessary
