services:
  # Java App Service
  - type: web
    name: java-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080

  # Prometheus Service
  - type: web
    name: prometheus
    env: image
    image:
      url: prom/prometheus:v2.44.0
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: prometheus-data
      mountPath: /etc/prometheus

  # Grafana Service
  - type: web
    name: grafana
    env: image
    image:
      url: grafana/grafana:9.5.2
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000
    disk:
      name: grafana-data
      mountPath: /etc/grafana
