name: Build and Deploy

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Ensure execute permissions for mvnw
        run: chmod +x mvnw
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: |
          ./mvnw test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
